from flask import Flask, render_template, request, jsonify
from pymongo import MongoClient

app = Flask(__name__)

client = MongoClient('localhost', 27017) # mongoDB의 27017 포트로 들어감
db = client.dbGongchaTest   # 'dbGongchaTest'라는 이름의 db 생성

def make_order_db(no, d, pro, tpri):
    number = no
    transaction_date = d
    date_split = transaction_date.split('-')
    date_list = date_split[:3]
    date_list.append(number)
    receipt_number = ''.join(date_list)
    products = pro  # [[products, amount, per_price, *options], ...]
    total_price = tpri

    order = {'number': number, 'receipt_number': receipt_number, 'products': products,
             'total_price': total_price}

    db.order.insert_one(order)

def make_pay_db(no, d, dpri, rpri):
    number = no
    transaction_date = d  # 거래 날짜
    date_split = transaction_date.split('-')
    date_list = date_split[:3]
    date_list.append(number)
    receipt_number = ''.join(date_list)  # 영수증 번호
    discount_price = dpri  # 할인 금액
    real_price = rpri  # 결제 금액 (메뉴 가격 - 할인 금액)

    pay = {'receipt_number': receipt_number, 'transaction_date': transaction_date, 'discount_price': discount_price,
           'real_price': real_price}

    db.pay.insert_one(pay)

def make_payments_db(): # order DB + pay DB = payments DB 만들기
    # 1. order DB에서 주문 정보 가져오기
    order_db = list(db.order.find({}, {'_id': 0}))

    for order in order_db:
        number = order['number']
        receipt_number = order['receipt_number']
        order_state = False  # 주문 처리 상태
        transaction_date = 0
        products = order['products']
        total_price = order['total_price']
        discount_price = 0
        real_price = 0

        payments = {'number': number, 'receipt_number': receipt_number, 'order_state': order_state,
                    'transaction_date': transaction_date, 'products': products, 'total_price': total_price,
                    'discount_price': discount_price, 'real_price': real_price}
        db.payments.insert_one(payments)

    # 2. pay DB에서 결제 정보 가져오기
    pay_db = list(db.pay.find({}, {'_id': 0}))

    for pay in pay_db:
        receipt_number = pay['receipt_number']
        transaction_date = pay['transaction_date']
        discount_price = pay['discount_price']
        real_price = pay['real_price']

        db.payments.update_one({'receipt_number': receipt_number}, {
            '$set': {'transaction_date': transaction_date, 'discount_price': discount_price, 'real_price': real_price}})


test_data = [{'no': '0001',
        'd': '2020-11-28-09:37',
        'pro': [{'product':'다크초코 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}, {'product':'딸기 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 5000,
        'rpri': 5000,
          },
        {'no': '0002',
        'd': '2020-11-28-09:37',
        'pro': [{'product':'얼그레이 밀크티(L)', 'amount':2, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 600,
        'rpri': 9400
         },
         {'no': '0001',
        'd': '2020-11-29-09:37',
        'pro': [{'product':'얼그레이 밀크티(J)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 5000,
        'dpri': 600,
        'rpri': 4400
         },
        {'no': '0002',
        'd': '2020-11-29-09:37',
        'pro': [{'product':'다크초코 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}, {'product':'딸기 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 5000,
        'rpri': 5000,
          },
        {'no': '0001',
        'd': '2020-11-30-09:37',
        'pro': [{'product':'얼그레이 밀크티(J)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 5000,
        'dpri': 600,
        'rpri': 4400
         },
        {'no': '0002',
        'd': '2020-11-30-09:37',
        'pro': [{'product':'다크초코 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}, {'product':'딸기 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 5000,
        'rpri': 5000,
          },
        {'no': '0003',
        'd': '2020-11-30-09:37',
        'pro': [{'product':'얼그레이 밀크티(L)', 'amount':2, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 600,
        'rpri': 9400
         },
        {'no': '0001',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'블랙 밀크티(J)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 5000,
        'dpri': 0,
        'rpri': 5000
         },
        {'no': '0002',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'다크초코 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}, {'product':'딸기 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 5000,
        'rpri': 5000,
          },
        {'no': '0003',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'얼그레이 밀크티(L)', 'amount':2, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 600,
        'rpri': 9400
         },
        {'no': '0004',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'블랙 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}, {'product':'얼그레이 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 3000,
        'rpri': 7000,
          },
        {'no': '0001',
        'd': '2020-12-02-09:37',
        'pro': [{'product':'얼그레이 밀크티(L)', 'amount':2, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 600,
        'rpri': 9400
         },
        {'no': '0002',
        'd': '2020-12-02-09:37',
        'pro': [{'product':'다크초코 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}, {'product':'딸기 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 5000,
        'rpri': 5000,
          }
        ]

test_data2 = [{'no': '0001',
               'd': '2020-11-01-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-02-09:37',
               'pro': [{'product': '얼그레이 밀크티(L)', 'amount': 2, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 600,
               'rpri': 9400
               },
              {'no': '0001',
               'd': '2020-11-03-09:37',
               'pro': [{'product': '얼그레이 밀크티(J)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 5000,
               'dpri': 600,
               'rpri': 4400
               },
              {'no': '0001',
               'd': '2020-11-04-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-05-09:37',
               'pro': [{'product': '얼그레이 밀크티(J)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 5000,
               'dpri': 600,
               'rpri': 4400
               },
              {'no': '0001',
               'd': '2020-11-06-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-07-09:37',
               'pro': [{'product': '얼그레이 밀크티(L)', 'amount': 2, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 600,
               'rpri': 9400
               },
              {'no': '0001',
               'd': '2020-11-08-09:37',
               'pro': [{'product': '블랙 밀크티(J)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 5000,
               'dpri': 0,
               'rpri': 5000
               },
              {'no': '0001',
               'd': '2020-11-09-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-10-09:37',
               'pro': [{'product': '얼그레이 밀크티(L)', 'amount': 2, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 600,
               'rpri': 9400
               },
              {'no': '0001',
               'd': '2020-11-11-09:37',
               'pro': [{'product': '블랙 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '얼그레이 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 3000,
               'rpri': 7000,
               },
              {'no': '0001',
               'd': '2020-11-12-09:37',
               'pro': [{'product': '얼그레이 밀크티(L)', 'amount': 2, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 600,
               'rpri': 9400
               },
              {'no': '0001',
               'd': '2020-11-13-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-14-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-15-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-16-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-17-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-18-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-19-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-20-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-21-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-22-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-23-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-24-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-25-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-26-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-27-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-28-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-29-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-11-30-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-01-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-02-09:37',
               'pro': [{'product': '얼그레이 밀크티(L)', 'amount': 2, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 600,
               'rpri': 9400
               },
              {'no': '0001',
               'd': '2020-12-03-09:37',
               'pro': [{'product': '얼그레이 밀크티(J)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 5000,
               'dpri': 600,
               'rpri': 4400
               },
              {'no': '0001',
               'd': '2020-12-04-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-05-09:37',
               'pro': [{'product': '얼그레이 밀크티(J)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 5000,
               'dpri': 600,
               'rpri': 4400
               },
              {'no': '0001',
               'd': '2020-12-06-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-07-09:37',
               'pro': [{'product': '얼그레이 밀크티(L)', 'amount': 2, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 600,
               'rpri': 9400
               },
              {'no': '0001',
               'd': '2020-12-08-09:37',
               'pro': [{'product': '블랙 밀크티(J)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 5000,
               'dpri': 0,
               'rpri': 5000
               },
              {'no': '0001',
               'd': '2020-12-09-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-10-09:37',
               'pro': [{'product': '얼그레이 밀크티(L)', 'amount': 2, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 600,
               'rpri': 9400
               },
              {'no': '0001',
               'd': '2020-12-11-09:37',
               'pro': [{'product': '블랙 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '얼그레이 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 3000,
               'rpri': 7000,
               },
              {'no': '0001',
               'd': '2020-12-12-09:37',
               'pro': [{'product': '얼그레이 밀크티(L)', 'amount': 2, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 600,
               'rpri': 9400
               },
              {'no': '0001',
               'd': '2020-12-13-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-14-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-15-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-16-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-17-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-18-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-19-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-20-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-21-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-22-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-23-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-24-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-25-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-26-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-27-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-28-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-29-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-30-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               },
              {'no': '0001',
               'd': '2020-12-31-09:37',
               'pro': [{'product': '다크초코 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']},
                       {'product': '딸기 밀크티+펄(L)', 'amount': 1, 'per_price': 5000,
                        'options': ['COLD(포장)', 'Regular Ice', '50%']}],
               'tpri': 10000,
               'dpri': 5000,
               'rpri': 5000,
               }
              ]

test_data3 = [{'no': '0001',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'블랙 밀크티(J)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%', '밀크폼']}],
        'tpri': 5000,
        'dpri': 0,
        'rpri': 5000
         },
        {'no': '0002',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'다크초코 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}, {'product':'딸기 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 5000,
        'rpri': 5000,
          },
        {'no': '0003',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'얼그레이 밀크티(L)', 'amount':2, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%', '펄']}],
        'tpri': 10000,
        'dpri': 600,
        'rpri': 9400
         },
        {'no': '0004',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'블랙 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%', '펄']}, {'product':'얼그레이 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 3000,
        'rpri': 7000,
          },
        {'no': '0005',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'얼그레이 밀크티(L)', 'amount':2, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%', '화이트펄']}],
        'tpri': 10000,
        'dpri': 600,
        'rpri': 9400
         },
        {'no': '0006',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'블랙 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}, {'product':'얼그레이 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 10000,
        'dpri': 3000,
        'rpri': 7000,
          },
        {'no': '0007',
        'd': '2020-12-01-09:37',
        'pro': [{'product':'블랙 밀크티+펄(L)', 'amount':1, 'per_price':5000, 'options': ['COLD(포장)', 'Regular Ice', '50%']}],
        'tpri': 5000,
        'dpri': 600,
        'rpri': 4400,
          }
        ]

db.order.delete_many({})
db.pay.delete_many({})
db.payments.delete_many({})

for data in test_data3:
    no = data['no']
    d = data['d']
    pro = data['pro']
    tpri = data['tpri']
    dpri = data['dpri']
    rpri = data['rpri']

    make_order_db(no, d, pro, tpri)
    make_pay_db(no, d, dpri, rpri)

make_payments_db()

